name: Test Dummy Class

on: [ push, pull_request ]


jobs:
  check:
    name: Build & Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: sudo apt-get install gtest zip
      - name: Build
        run:
          make && cd build
          zip programs.zip main test
      - name: Run the Test
        run:
          make check
      - name: Upload Programs
        uses: actions/upload-artifact@v4
        with:
          name: programs
          path: build/programs.zip

  release:
    if: ${{github.ref == 'refs/heads/main' && github.event_name == 'push'}}
    name: Make Release
    runs-on: ubuntu-latest
    needs: [ check ]
    steps:
      - name: Download programs
        uses: actions/download-artifact@v4
        with:
          name: programs
      - name: Create release
        uses: "crowbarmaster/GH-Automatic-Releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN}}
          automatic_release_tag: latest
          prerelease: true
          title: "Test"
          files: ./build/programs.zip
