#!/usr/bin/env bash

clear
if [ -d "Build" ]; then
  rm -rf Build
fi

mkdir -p Build && cd Build

c++ -c ../Lib/fizzbuzz.cpp -I./fizzbuzz -o lib.o
c++ -c ../Test/test.cpp -o test.o -I../Lib
c++ -o index ../Src/index.cpp lib.o 

c++ lib.o test.o -lunity -o test

./test

./index