name: MAIN-CI Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Build & Test.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build_install
        run: |
          sudo apt-get install build-essential
          sudo apt-get install cmake python3-dev
          sudo apt-get install libgtest-dev

      - name: CI-exec_3-CMake
        run: |
          cd ./subDir/CI/exec_3
          mkdir -p build
          cd ./build
          cmake .. && make && ./run_test
          make test

      - name: CI-exec_4-CMake
        run: |
          cd ./subDir/CI/exec_4
          mkdir -p build
          cd ./build
          cmake .. && make && ./run_test
          make test

      - name: CI-exec_5-CMake
        run: |
          cd ./subDir/CI/exec_5
          mkdir -p build
          cd ./build
          cmake .. && make && ./run_test
          make test
